dev text detection module
phamquiluan/Go5-Project pull request #9
Opened 2022-07-30 14:48 UTC by ankhanh-vni

2022-08-01 10:15 UTC, phamquiluan commented
sửa lại tên PR đi em @ankhanh-vni ,

"Add text detection module"

2022-08-01 10:16 UTC, phamquiluan requested changes
- sửa tên PR 
- thêm hướng dẫn cài đặt
- thêm 1 file jupyter notebook hiển thị cách chạy bao gồm đọc input, xử lý input bằng model, in kết quả output

2022-08-01 10:16 UTC, phamquiluan commented on text_detection/text_detection.py
> +import mmcv
requirement + hướng dẫn cài đặt mấy thằng này đâu? viết readme đi em @ankhanh-vni

2022-08-01 10:39 UTC, ankhanh-vni commented on text_detection/text_detection.py
> +import mmcv
dạ vâng ạ

2022-08-28 18:39 UTC, ankhanh-vni commented on text_detection/text_detection.py
> +#path to mmocr library
wtf

2022-08-31 17:10 UTC, phamquiluan approved these changes
LGTM!

2022-08-31 17:10 UTC, merged